exclude: ^tests/resources/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        exclude: 'notebooks/*'
      - id: check-json
        exclude: 'notebooks/*'
      - id: check-toml
        exclude: 'notebooks/*'
      - id: check-yaml
        exclude: 'notebooks/*'
      - id: end-of-file-fixer
        exclude: 'notebooks/*'
      - id: trailing-whitespace
        exclude: 'notebooks/*'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes, --ignore=F821]
        exclude: 'notebooks/*'
      - id: ruff-format
        exclude: 'notebooks/*'
